# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/P731A20/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/zte/P731A20/proprietary/bin/engpc:system/bin/engpc \
    vendor/zte/P731A20/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    vendor/zte/P731A20/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    vendor/zte/P731A20/proprietary/bin/modemd:system/bin/modemd \
    vendor/zte/P731A20/proprietary/bin/nvitemd:system/bin/nvitemd \
    vendor/zte/P731A20/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/zte/P731A20/proprietary/bin/refnotify:system/bin/refnotify \
	vendor/zte/P731A20/proprietary/bin/rild:system/bin/rild \
	vendor/zte/P731A20/proprietary/bin/rilproxyd:system/bin/rilproxyd \
    vendor/zte/P731A20/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/zte/P731A20/proprietary/lib/drm/libdrmomaplugin.so:system/lib/drm/libdrmomaplugin.so \
    vendor/zte/P731A20/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/zte/P731A20/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/zte/P731A20/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/zte/P731A20/proprietary/lib/hw/audio.primary.sc8830.so:system/lib/hw/audio.primary.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/audio_policy.sc8830.so:system/lib/hw/audio_policy.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/camera2.sc8830.so:system/lib/hw/camera2.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/fm.sc8830.so:system/lib/hw/fm.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/zte/P731A20/proprietary/lib/hw/gralloc.sc8830.so:system/lib/hw/gralloc.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/hwcomposer.sc8830.so:system/lib/hw/hwcomposer.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/lights.sc8830.so:system/lib/hw/lights.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/sprd_gsp.sc8830.so:system/lib/hw/sprd_gsp.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/modules/mali.ko:system/lib/modules/mali.ko \
    vendor/zte/P731A20/proprietary/lib/libatchannel.so:system/lib/libatchannel.so \
    vendor/zte/P731A20/proprietary/lib/libaudiopolicy.so:system/lib/libaudiopolicy.so \
    vendor/zte/P731A20/proprietary/lib/libboost.so:system/lib/libboost.so \
    vendor/zte/P731A20/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/zte/P731A20/proprietary/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/zte/P731A20/proprietary/lib/libdumpdata.so:system/lib/libdumpdata.so \
    vendor/zte/P731A20/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/zte/P731A20/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/zte/P731A20/proprietary/lib/libiwnpi.so:system/lib/libiwnpi.so \
    vendor/zte/P731A20/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/zte/P731A20/proprietary/lib/libnvexchange.so:system/lib/libnvexchange.so \
    vendor/zte/P731A20/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/zte/P731A20/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/zte/P731A20/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/zte/P731A20/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/zte/P731A20/proprietary/lib/librilproxy.so:system/lib/librilproxy.so \
    vendor/zte/P731A20/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/zte/P731A20/proprietary/lib/libsprd_agps_agent.so:system/lib/libsprd_agps_agent.so \
    vendor/zte/P731A20/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/zte/P731A20/proprietary/lib/libtinyxml.so:system/lib/libtinyxml.so \
    vendor/zte/P731A20/proprietary/lib/libuvdenoise.so:system/lib/libuvdenoise.so \
    vendor/zte/P731A20/proprietary/lib/libvbeffect.so:system/lib/libvbeffect.so \
    vendor/zte/P731A20/proprietary/lib/libvbpga.so:system/lib/libvbpga.so \
    vendor/zte/P731A20/proprietary/lib/libvtmanager.so:system/lib/libvtmanager.so \
    vendor/zte/P731A20/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/zte/P731A20/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/zte/P731A20/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/zte/P731A20/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
