# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/P731A20/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/zte/P731A20/proprietary/bin/engpc:system/bin/engpc \
    vendor/zte/P731A20/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    vendor/zte/P731A20/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    vendor/zte/P731A20/proprietary/bin/modemd:system/bin/modemd \
    vendor/zte/P731A20/proprietary/bin/nvitemd:system/bin/nvitemd \
    vendor/zte/P731A20/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/zte/P731A20/proprietary/bin/refnotify:system/bin/refnotify \
	vendor/zte/P731A20/proprietary/bin/rild_sp:system/bin/rild_sp \
	vendor/zte/P731A20/proprietary/bin/rilproxyd:system/bin/rilproxyd \
    vendor/zte/P731A20/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/zte/P731A20/proprietary/lib/drm/libdrmomaplugin.so:system/lib/drm/libdrmomaplugin.so \
    vendor/zte/P731A20/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/zte/P731A20/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/zte/P731A20/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/zte/P731A20/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/camera2.sc8830.so:system/lib/hw/camera2.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/zte/P731A20/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/zte/P731A20/proprietary/lib/libboost.so:system/lib/libboost.so \
    vendor/zte/P731A20/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/zte/P731A20/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/zte/P731A20/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/zte/P731A20/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/zte/P731A20/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/zte/P731A20/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/zte/P731A20/proprietary/lib/libril_sp.so:system/lib/libril_sp.so \
    vendor/zte/P731A20/proprietary/lib/librilproxy.so:system/lib/librilproxy.so \
    vendor/zte/P731A20/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/zte/P731A20/proprietary/lib/libsprd_agps_agent.so:system/lib/libsprd_agps_agent.so \
    vendor/zte/P731A20/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/zte/P731A20/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/zte/P731A20/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/zte/P731A20/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
